query UserBookmarks($userId: ID!) {
	userBookmarks(userId: $userId) {
		_id
		title
		text
		slug
		views
		created
		user {
			_id
			firstName
			lastName
			username
			avatar {
				color
				images
			}
		}
		comments {
			_id
			replies {
				_id
			}
		}
	}
}
